stages:
    - mrcop
    - ci

# Check merge requests for "conventional" message format and required jira ticket(s)
# Enabling non-squash
mrcop:
  image: gitlab-master.nvidia.com:5005/ngc/common/mr-cop/mr-cop:latest-amd64
  stage: mrcop
  tags:
    - os/linux
    - type/docker
# rules:
  # - if: $CI_PIPELINE_SOURCE == "merge_request_event"
  variables:
    JIRA_USR: $JIRA_USERNAME
    JIRA_PSW: $JIRA_PASSWORD
    JIRA_HOST: "jirasw.nvidia.com"
    NV_MR_COP_SKIP_SQUASH_REQUIRED_CHECK: "true"
    ALLOW_NO_REF: "true"
  script:
    # This is a fugly hack.
    # The command should be: node index.js $CI_PROJECT_ID $CI_MERGE_REQUEST_IID
    # However, we work from forks and we need this pipeline tagged "fork" not "merge-request"
    # So I had to comment out the "rules" above, and then simulate the MR variables
    # I really don't follow, but this works.  Note the project ID must be the MR target project ID
    # It seems the vars are made available asynchronously, so the sleep improves the odds they will be available
    - |
      PROJECT=82853
      MR_ID=${CI_OPEN_MERGE_REQUESTS##*\!}
      set -x
      for i in {1..20}; do
        test -n "$MR_ID" && break
        sleep 10
        MR_ID=$(curl -s --header "PRIVATE-TOKEN: $GL_TOKEN" "$CI_API_V4_URL/projects/$PROJECT/merge_requests?source_project_id=$CI_PROJECT_ID&source_branch=$CI_COMMIT_BRANCH&state=opened" | grep -Po '"iid": *\K[0-9]+' || true)
      done
      cd /usr/bin/mrcop
      node index.js 82853 $MR_ID
  retry:
    when: always
    max: 2
